nav:
  - section:
      links:
        - item:
            path: index
            display: Home
        - item:
            path: why
            display: Why?
        - item:
            path: install
            display: Install
  - section:
      display: Guides
      links:
        - item:
            path: syntax-overview
            display: Syntax Overview
        - item: 
            path: operators
            display: Operators
        - item: 
            path: runtime
            display: Runtime